	DROP TABLE IF EXISTS incidents;
	CREATE TABLE incidents (
		incident_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		dr_no VARCHAR(24),
		date_reported DATE,
		date_occ DATE,
		time_occ DATE,
		area_code INT,
		area_name VARCHAR(40),
		report_district_no INT,
		part12 INT,
		crime_code INT,
		crime_code_description VARCHAR(200),
		mo_codes VARCHAR(200),
		victim_age INT,
		victim_sec VARCHAR(3),
		victim_descent VARCHAR(3),
		premis_code INT,
		premis_description VARCHAR(200),
		weapon_code INT,
		weapon_description VARCHAR(200),
		crime_status VARCHAR(5),
		crime_status_description VARCHAR(200),
		crime_code1 INT,
		crime_code2 INT,
		crime_code3 INT,
		crime_code4 INT,
		location_name VARCHAR(200),
		location_cross_street VARCHAR(40),
		latitude FLOAT,
		longitude FLOAT
	);