DROP TABLE IF EXISTS incidents;
CREATE TABLE incidents (
	incident_id VARCHAR(32),
	offence_code INT DEFAULT NULL,
	cr_number VARCHAR(16),
	datetime_dispatch DATETIME,
	nibrs_code VARCHAR(16),
	victims INT DEFAULT 0,
	crime_name1 VARCHAR(200),
	crime_name2 VARCHAR(200),
	crime_name3 VARCHAR(200),
	police_district_name VARCHAR(200),
	block_address VARCHAR(200),
	city VARCHAR(50),
	state VARCHAR(2),
	zip VARCHAR(5),
	agency VARCHAR(50),
	place VARCHAR(100),
	sector VARCHAR(50),
	beat VARCHAR(50),
	pra VARCHAR(50),
	address_number VARCHAR(50),
	street_prefix VARCHAR(16),
	street_name VARCHAR(50),
	street_suffix VARCHAR(16),
	street_type VARCHAR(16),
	datetime_start DATETIME,
	datetime_end DATETIME,
	latitude FLOAT,
	longitude FLOAT,
	police_district_number VARCHAR(16),
	incident_location VARCHAR(64),
	INDEX( incident_id )
);